### ISSUE TITLE
Spamming enter and exit on the screenshot menu crashes the game.

### ISSUE THREAD

**Issue by CallMeEchoCodes** [SpiritGameStudios/Snapper#1]
This appears to be another way of triggering the close while opening bug.

**Comment by Thinkseal** [comment]
Just successfully reproduced it

**Comment by worldwidepixel** [comment]
In my experience it takes quite a bit of effort to reproduce. Hopefully we can fix it for 1.1

**Comment by Thinkseal** [comment]
> In my experience it takes quite a bit of effort to reproduce. Hopefully we can fix it for 1.1

I can agree it was a lot of effort

**Comment by CallMeEchoCodes** [comment]
Yeah it is kinda hard. I believe the issue is it trying to load twice at the same time.

**Comment by worldwidepixel** [comment]
![image](https://github.com/user-attachments/assets/87e9a6b2-36ee-4d12-b316-fff27d6ba60e)
Can still reproduce as of Dec 1.
