### ISSUE TITLE
Crash upon pressing latest screenshot key if the screenshots folder is empty

### ISSUE THREAD

**Issue by notrohit1702** [SpiritGameStudios/Snapper#10]
When the open latest screenshot key is pressed in-game, if no screenshots have been taken before (ie. the screenshot folder is empty), the game crashes.

This could cause a crash if you press the key by accident in a new instance. I can confirm this doesn't happen when there is at least one screenshot taken beforehand.

I am using:
- Minecraft 1.21.1
- Fabric Loader 0.16.9
- [Fabric API 0.107.0](https://modrinth.com/mod/fabric-api/version/0.107.0+1.21.1)
- [Snapper 1.0.0](https://modrinth.com/mod/snapper/version/1.0.0)

latest.log: https://mclo.gs/sMI6RKU
Crash report: https://mclo.gs/1Ii7w2Z

**Comment by worldwidepixel** [comment]
Honestly disappointed that I didn't make a check for this, assuming I haven't

**Comment by worldwidepixel** [comment]
Just checked, yeah I think I see the issue.

We're a little tied up in [Modfest 1.21](https://modfest.net/1.21) right now, but in the near future we'll get back on Snapper development.

**Comment by worldwidepixel** [comment]
Work has lightened up- Finally fixing.

**Comment by worldwidepixel** [comment]
I can't seem to reproduce it? I'll see what I can do.

**Comment by worldwidepixel** [comment]
Turns out [Hama fixed it a couple months ago!](https://github.com/SpiritGameStudios/Snapper/commit/c7ad7d8831ee10507dfc866dc9216237f0bf6687)

I'll make sure this is closed when 1.0.1 releases.

**Comment by worldwidepixel** [comment]
Actually- might as well do it now... Thank you!
