### ISSUE TITLE
Snapper button shows in the F3+Escape pause menu

### ISSUE THREAD

**Issue by mekb-turtle** [SpiritGameStudios/Snapper#12]
Pressing F3+Escape will pause without bringing up a menu, but the button for Snapper still shows

![Snapper button on pause screen](https://github.com/user-attachments/assets/ca2a2d6f-714a-4cf6-a995-0778a1e4a14f)

**Comment by worldwidepixel** [comment]
Currently fixing; seems like a pretty simple solve, luckily!
