### ISSUE TITLE
Panorama creates a glitchy screenshot if taken in third-person perspective

### ISSUE THREAD

**Issue by mekb-turtle** [SpiritGameStudios/Snapper#3]
To recreate:
1. Go in to front facing or back facing third-person perspective
2. Press the keybind to create a panorama screenshot
3. Preview the screenshot

![glitchy screenshot](https://github.com/user-attachments/assets/cdfd2275-81ae-4276-afee-8a20eacf01ac)

**Comment by worldwidepixel** [comment]
I didn't realise that was even possible...

**Comment by HamaIndustries** [comment]
b1ce4b5 it is now
