### ISSUE TITLE
Copy the screenshot once it's taken

### ISSUE THREAD

**Issue by mekb-turtle** [SpiritGameStudios/Snapper#4]
I feel like a configurable option to do this would be nice as pressing O and clicking Copy is tedious every time because I share screenshots frequently

**Comment by worldwidepixel** [comment]
This will be added in 1.1.

**Comment by HamaIndustries** [comment]
implemented in [96cc791](https://github.com/SpiritGameStudios/Snapper/commit/96cc791453d20bc7994a8b6076d4bb1304ccd552), needs config option

**Comment by worldwidepixel** [comment]
Fully completed in [latest commit](https://github.com/SpiritGameStudios/Snapper/commit/19d2e8b52a64dcd0c43ae55420f751d05de98fe0), with config option; closing
